# Generated by Django 3.2.5 on 2021-07-12 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('nb_choice', models.IntegerField(blank=True, null=True)),
                ('nb_all_vote', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('nb_vote', models.IntegerField(default=0)),
                ('percent_vote', models.IntegerField(blank=True, default=0, null=True)),
                ('num_id_choice', models.IntegerField(blank=True, null=True)),
                ('voters_names', models.CharField(default='', max_length=120)),
                ('vote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votes.vote')),
            ],
        ),
    ]
